dist: xenial
sudo: false

matrix:
  fast_finish: true

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "3.9-dev"

before_install:
  - pip freeze
  - travis_retry pip install --upgrade pip
  - travis_retry pip install --upgrade pycodestyle
  - travis_retry pip install --upgrade pylint
  - pip freeze


script:
  - pycodestyle --max-line-length=100 --statistics check_x509_expire
  - pylint check_x509_expire
  - ./check_x509_expire -s example.com -p 443 -w 28 -c 21
